services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
