services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    volumes:
      - db-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    container_name: valkey-cache
    ports:
      - "6379:6379"
    command: valkey-server --requirepass valkey_password
    volumes:
      - valkey-data:/data
    restart: unless-stopped

volumes:
  db-data:
  valkey-data:
