ALTER TABLE IF EXISTS users
ADD COLUMN role_id BIGINT REFERENCES roles(id) DEFAULT 1;

UPDATE users
SET role_id = (
    SELECT ID FROM ROLES WHERE name = 'user'
);

ALTER TABLE IF EXISTS users
ALTER COLUMN role_id DROP DEFAULT;

ALTER TABLE IF EXISTS users
ALTER COLUMN role_id SET NOT NULL;
